update main.py to render QR codes in GitHub PRs
GlueOps/pull-request-bot pull request #13
Opened 2023-07-04 21:44 UTC by Mbaoma

2023-07-04 21:48 UTC, venkatamutyala commented on main.py
> +import qrcode
i don't think this is being used

2023-07-04 21:48 UTC, venkatamutyala commented on main.py
> +import qrcode
same as above

2023-07-04 21:48 UTC, venkatamutyala commented on main.py
> +import base64
same

2023-07-04 21:48 UTC, venkatamutyala commented on main.py
> +buffer = BytesIO()
same

2023-07-04 21:49 UTC, venkatamutyala commented on requirements.txt
i don't think there should be any changes in this file since the service is going to be external to this repo.

2023-07-04 21:50 UTC, venkatamutyala requested changes
left a few comments. happy to jump on a call.

2023-07-04 21:57 UTC, fernandoataoldotcom commented on main.py
> +    qr_code_url = f'https://mbaoma-ominous-yodel-7pj9wxg69jx2w6j5-8000.preview.app.github.dev/v1/qr?url={external_urls[0]}'
this line will call the endpoint of the API you deploy from the other repo

2023-07-17 18:56 UTC, venkatamutyala requested changes

2023-07-17 18:56 UTC, venkatamutyala commented on main.py
> +    qr_code_url = f'https://qr-code-generator.test-80-np.pluto.onglueops.rocks/v1/qr?url={external_urls[0]}'
The captain domain will vary between clouds. This will need to be an environment variable or ideally grabbed from some existing configmap inside the cluster.

2023-07-17 18:56 UTC, venkatamutyala commented on README.md
> +export AWS_ACCESS_KEY_ID=<some-value>
I would get rid of the AWS specific instructions as we should be able to debug this across clouds.

2023-07-17 20:03 UTC, Mbaoma commented on README.md
> +export AWS_ACCESS_KEY_ID=<some-value>
noted

2023-07-17 20:45 UTC, Mbaoma commented on main.py
> +    qr_code_url = f'https://qr-code-generator.test-80-np.pluto.onglueops.rocks/v1/qr?url={external_urls[0]}'
i setup .env file and added instructions in the README file. I tested the app and it works

2023-07-17 20:55 UTC, venkatamutyala commented on main.py
> +    qr_code_url = f'https://qr-code-generator.{domain}/v1/qr?url={external_urls[0]}'
I think you will want: CAPTAIN_DOMAIN_K8S_CONFIGMAP_NAME

2023-07-17 20:56 UTC, venkatamutyala commented on main.py
> +    qr_code_url = f'https://qr-code-generator.{domain}/v1/qr?url={external_urls[0]}'
See the code above @Mbaoma

2023-07-17 21:12 UTC, Mbaoma commented on main.py
> +    qr_code_url = f'https://qr-code-generator.{domain}/v1/qr?url={external_urls[0]}'
noted

2023-07-17 21:33 UTC, venkatamutyala commented on main.py
> +    qr_code_url = f'https://qr-code-generator.{domain}/v1/qr?url={external_urls[0]}'
Please take a clsoer look: https://github.com/GlueOps/pull-request-bot/blob/01673038103e48ff68e49f6236dc1477eae31e72/main.py#L62

2023-07-17 21:34 UTC, venkatamutyala commented on README.md
> +aws eks update-kubeconfig --region us-west-2 --name captain-cluster --role-arn arn:aws:iam::<some-value>:role/captain-role
We will want to pull out this EKS command as well given it's cloud specific. It's covered in these docs that are specific for the cloud: https://github.com/GlueOps/terraform-module-cloud-aws-kubernetes-cluster/wiki

I think it's worth mentioning something along the lines of needing to be authenticated to the captain cluster

2023-07-18 15:08 UTC, venkatamutyala requested changes
left comments for you

2023-07-18 15:25 UTC, venkatamutyala commented on main.py
> +CAPTAIN_DOMAIN_K8S_CONFIGMAP_NAME = os.getenv("DOMAIN")
@Mbaoma this is defined twice in the code.

2023-07-18 16:25 UTC, merged